import {useCallback,useEffect,useMemo,useState,type FormEvent} from "react";
import "./learning-schedule.css";

const API=import.meta.env.VITE_API_URL??"http://localhost:4000/api";
type ViewMode="day"|"work_week"|"week"|"month";
type TrainingEvent={id:string;title:string;description?:string;location?:string;trainer?:string;start_date:string;end_date:string;start_time:string;end_time:string;capacity?:number;status:"draft"|"scheduled"|"cancelled"};
const monthNames=["January","February","March","April","May","June","July","August","September","October","November","December"],weekdayNames=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
const isoDate=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
const dateInputValue=(value?:string)=>value?value.slice(0,10):"",timeInputValue=(value?:string)=>value?value.slice(0,5):"";
const addDays=(date:Date,amount:number)=>{const next=new Date(date);next.setDate(next.getDate()+amount);return next},startOfWeek=(date:Date)=>addDays(date,-date.getDay());
const formatTime=(value:string)=>{const [hour,minute]=value.split(":").map(Number);return new Date(2000,0,1,hour,minute).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})},sameDate=(a:Date,b:Date)=>isoDate(a)===isoDate(b);

export default function LearningSchedule({token,role}:{token:string;role:string}){
  const [cursor,setCursor]=useState(()=>new Date()),[selectedDate,setSelectedDate]=useState(()=>new Date()),[view,setView]=useState<ViewMode>("month"),[events,setEvents]=useState<TrainingEvent[]>([]),[selected,setSelected]=useState<TrainingEvent|null>(null),[draftDate,setDraftDate]=useState(""),[showForm,setShowForm]=useState(false),[error,setError]=useState("");
  const canManage=["admin","administrator","system_administrator","hr"].includes(role);
  const request=useCallback(async(path:string,options?:RequestInit)=>{const response=await fetch(`${API}${path}`,{...options,headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json",...(options?.headers??{})}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error??"Unable to complete request");return body},[token]);
  const visibleDays=useMemo(()=>{if(view==="day")return[new Date(cursor)];const weekStart=startOfWeek(cursor);if(view==="work_week")return Array.from({length:6},(_,index)=>addDays(weekStart,index+1));if(view==="week")return Array.from({length:7},(_,index)=>addDays(weekStart,index));const first=new Date(cursor.getFullYear(),cursor.getMonth(),1),start=startOfWeek(first);return Array.from({length:42},(_,index)=>addDays(start,index))},[cursor,view]);
  const rangeStart=isoDate(visibleDays[0]),rangeEnd=isoDate(visibleDays.at(-1)??visibleDays[0]);
  const load=useCallback(async()=>{try{const loaded=await request(`/learning/training-events?from=${rangeStart}&to=${rangeEnd}`) as TrainingEvent[];setEvents(loaded.map(item=>({...item,start_date:dateInputValue(item.start_date),end_date:dateInputValue(item.end_date),start_time:timeInputValue(item.start_time),end_time:timeInputValue(item.end_time)})))}catch(reason){setError(reason instanceof Error?reason.message:"Unable to load schedule")}},[rangeStart,rangeEnd,request]);
  useEffect(()=>{void load()},[load]);
  const eventsFor=(day:Date,includeCancelled=false)=>{const key=isoDate(day);return events.filter(event=>event.start_date<=key&&event.end_date>=key&&(includeCancelled||event.status!=="cancelled"))};
  const openCreate=(day=selectedDate)=>{if(!canManage)return;setSelected(null);setDraftDate(isoDate(day));setShowForm(true)};
  const selectDay=(day:Date)=>{setSelectedDate(day);if(view==="day")setCursor(day)};
  const title=view==="month"?`${monthNames[cursor.getMonth()]} ${cursor.getFullYear()}`:view==="day"?cursor.toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric",year:"numeric"}):`${visibleDays[0].toLocaleDateString(undefined,{month:"short",day:"numeric"})} – ${visibleDays.at(-1)!.toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"})}`;
  const shift=(amount:number)=>setCursor(current=>view==="month"?new Date(current.getFullYear(),current.getMonth()+amount,1):addDays(current,amount*(view==="day"?1:7)));
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget),payload={title:form.get("title"),description:form.get("description"),location:form.get("location"),trainer:form.get("trainer"),startDate:form.get("startDate"),endDate:form.get("endDate"),startTime:form.get("startTime"),endTime:form.get("endTime"),capacity:form.get("capacity")?Number(form.get("capacity")):null,status:form.get("status")};try{await request(selected?`/learning/training-events/${selected.id}`:"/learning/training-events",{method:selected?"PATCH":"POST",body:JSON.stringify(payload)});setSelected(null);setShowForm(false);await load()}catch(reason){setError(reason instanceof Error?reason.message:"Unable to save training event")}};
  const cancelEvent=async()=>{if(!selected)return;try{await request(`/learning/training-events/${selected.id}`,{method:"PATCH",body:JSON.stringify({title:selected.title,description:selected.description??"",location:selected.location??"",trainer:selected.trainer??"",startDate:selected.start_date,endDate:selected.end_date,startTime:selected.start_time,endTime:selected.end_time,capacity:selected.capacity??null,status:"cancelled"})});setSelected(null);setShowForm(false);await load()}catch(reason){setError(reason instanceof Error?reason.message:"Unable to cancel event")}};
  const agendaDays=visibleDays.filter(day=>eventsFor(day,true).length>0);
  return <div className="schedule-page">
    <header className="schedule-header"><div><small>HUMAN RESOURCES</small><h1>L&amp;D Schedule</h1><p>Upcoming in-person training events and learning sessions.</p></div>{canManage&&<button onClick={()=>openCreate()}>+ Training Event</button>}</header>
    {error&&<div className="schedule-error">{error}<button onClick={()=>setError("")}>×</button></div>}
    <section className={`schedule-calendar view-${view}`}><header><button onClick={()=>{const today=new Date();setCursor(today);setSelectedDate(today)}}>Today</button><button aria-label="Previous period" onClick={()=>shift(-1)}>‹</button><button aria-label="Next period" onClick={()=>shift(1)}>›</button><label className="schedule-date-jump"><h2>{title}</h2><input type="date" aria-label="Jump to date" value={isoDate(cursor)} onClick={event=>event.currentTarget.showPicker?.()} onChange={event=>{if(!event.target.value)return;const [year,month,day]=event.target.value.split("-").map(Number),target=new Date(year,month-1,day);setCursor(target);setSelectedDate(target)}}/><span aria-hidden="true">▾</span></label><div className="schedule-views">{([['day','Day'],['work_week','Work Week'],['week','Week'],['month','Month']] as [ViewMode,string][]).map(([key,text])=><button key={key} className={view===key?"active":""} onClick={()=>setView(key)}>{text}</button>)}</div></header><div className="schedule-weekdays">{visibleDays.slice(0,view==="month"?7:visibleDays.length).map(day=><b className={day.getDay()===0?"sunday":""} key={`${day.getDay()}-${isoDate(day)}`}><span>{weekdayNames[day.getDay()]}</span>{view!=="month"&&<time>{day.getDate()}</time>}</b>)}</div><div className="schedule-grid">{visibleDays.map(day=><article tabIndex={0} className={`${view==="month"&&day.getMonth()!==cursor.getMonth()?"outside":""} ${sameDate(day,new Date())?"today":""} ${sameDate(day,selectedDate)?"selected":""} ${day.getDay()===0?"sunday":""}`} key={isoDate(day)} onClick={()=>selectDay(day)} onDoubleClick={()=>openCreate(day)}><time>{day.getDate()}</time><div>{eventsFor(day).map(item=><button key={item.id} className={item.status} onClick={event=>{event.stopPropagation();setSelectedDate(day);if(canManage){setSelected(item);setShowForm(true)}}}><b>{formatTime(item.start_time)}</b> {item.title}</button>)}</div></article>)}</div></section>
    <section className="schedule-agenda"><header><div><small>DAILY AGENDA</small><h2>Training schedule by day</h2></div><span>{events.length} event{events.length===1?"":"s"}</span></header>{agendaDays.length===0?<p>No training events in this period.</p>:<div>{agendaDays.map(day=><article key={isoDate(day)}><time><b>{day.getDate()}</b><span>{day.toLocaleDateString(undefined,{weekday:"short",month:"short"})}</span></time><div>{eventsFor(day,true).map(item=><button key={item.id} className={item.status} onClick={()=>{setSelectedDate(day);if(canManage){setSelected(item);setShowForm(true)}}}><i></i><span><b>{item.title}</b><small>{formatTime(item.start_time)} – {formatTime(item.end_time)} · {item.location||"Location not set"}{item.trainer?` · ${item.trainer}`:""}</small></span><em>{item.status}</em></button>)}</div></article>)}</div>}</section>
    {showForm&&canManage&&<div className="schedule-backdrop" onMouseDown={()=>setShowForm(false)}><form className="schedule-modal" onSubmit={submit} onMouseDown={event=>event.stopPropagation()}><header><div><small>LEARNING &amp; DEVELOPMENT</small><h2>{selected?"Edit Training Event":"Create Training Event"}</h2></div><button type="button" onClick={()=>setShowForm(false)}>×</button></header><div><label className="full">Event Title<input name="title" required defaultValue={selected?.title}/></label><fieldset className="full schedule-date-range"><legend>Date Range</legend><label>Start Date<input name="startDate" type="date" required defaultValue={selected?.start_date??draftDate??isoDate(selectedDate)}/></label><label>End Date<input name="endDate" type="date" required defaultValue={selected?.end_date??draftDate??isoDate(selectedDate)}/></label></fieldset><label>Start Time<input name="startTime" type="time" required defaultValue={selected?.start_time??"08:00"}/></label><label>End Time<input name="endTime" type="time" required defaultValue={selected?.end_time??"10:00"}/></label><label>Location<input name="location" defaultValue={selected?.location}/></label><label>Trainer<input name="trainer" defaultValue={selected?.trainer}/></label><label>Capacity<input name="capacity" type="number" min="1" defaultValue={selected?.capacity}/></label><label>Status<select name="status" defaultValue={selected?.status??"scheduled"}><option value="draft">Draft</option><option value="scheduled">Scheduled</option><option value="cancelled">Cancelled</option></select></label><label className="full">Description<textarea name="description" rows={4} defaultValue={selected?.description}/></label></div><footer>{selected&&selected.status!=="cancelled"&&<button type="button" className="danger" onClick={()=>void cancelEvent()}>Cancel Event</button>}<button type="button" onClick={()=>setShowForm(false)}>Close</button><button>Save Event</button></footer></form></div>}
  </div>
}
