import {useCallback,useEffect,useMemo,useState,type FormEvent} from "react";
import "./learning-schedule.css";

const API=import.meta.env.VITE_API_URL??"http://localhost:4000/api";
type TrainingEvent={id:string;title:string;description?:string;venue?:string;trainer?:string;starts_at:string;ends_at:string;capacity?:number;status:"draft"|"scheduled"|"cancelled"};
const monthTitle=(date:Date)=>`${["January","February","March","April","May","June","July","August","September","October","November","December"][date.getMonth()]} ${date.getFullYear()}`;
const localInput=(value:string)=>{const date=new Date(value),offset=date.getTimezoneOffset()*60000;return new Date(date.getTime()-offset).toISOString().slice(0,16)};

export default function LearningSchedule({token,role}:{token:string;role:string}){
  const [cursor,setCursor]=useState(()=>new Date()),[events,setEvents]=useState<TrainingEvent[]>([]),[selected,setSelected]=useState<TrainingEvent|null>(null),[showForm,setShowForm]=useState(false),[error,setError]=useState("");
  const canManage=role==="admin"||role==="hr";
  const request=useCallback(async(path:string,options?:RequestInit)=>{const response=await fetch(`${API}${path}`,{...options,headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json",...(options?.headers??{})}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error??"Unable to complete request");return body},[token]);
  const range=useMemo(()=>{const first=new Date(cursor.getFullYear(),cursor.getMonth(),1),start=new Date(first);start.setDate(1-first.getDay());const end=new Date(start);end.setDate(start.getDate()+42);return{start,end}},[cursor]);
  const load=useCallback(async()=>{try{setEvents(await request(`/learning/training-events?from=${range.start.toISOString()}&to=${range.end.toISOString()}`))}catch(reason){setError(reason instanceof Error?reason.message:"Unable to load schedule")}},[range,request]);
  useEffect(()=>{void load()},[load]);
  const days=useMemo(()=>Array.from({length:42},(_,index)=>{const day=new Date(range.start);day.setDate(day.getDate()+index);return day}),[range]);
  const eventsFor=(day:Date)=>events.filter(event=>{const date=new Date(event.starts_at);return date.getFullYear()===day.getFullYear()&&date.getMonth()===day.getMonth()&&date.getDate()===day.getDate()});
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget),payload={title:form.get("title"),description:form.get("description"),venue:form.get("venue"),trainer:form.get("trainer"),startsAt:new Date(String(form.get("startsAt"))).toISOString(),endsAt:new Date(String(form.get("endsAt"))).toISOString(),capacity:form.get("capacity")?Number(form.get("capacity")):null,status:form.get("status")};try{await request(selected?`/learning/training-events/${selected.id}`:"/learning/training-events",{method:selected?"PATCH":"POST",body:JSON.stringify(payload)});setSelected(null);setShowForm(false);await load()}catch(reason){setError(reason instanceof Error?reason.message:"Unable to save training event")}};
  const remove=async()=>{if(!selected||!confirm(`Remove ${selected.title}?`))return;try{await request(`/learning/training-events/${selected.id}`,{method:"DELETE"});setSelected(null);setShowForm(false);await load()}catch(reason){setError(reason instanceof Error?reason.message:"Unable to remove event")}};
  const shift=(amount:number)=>setCursor(current=>new Date(current.getFullYear(),current.getMonth()+amount,1));
  return <div className="schedule-page">
    <header className="schedule-header"><div><small>HUMAN RESOURCES</small><h1>L&amp;D Schedule</h1><p>Upcoming in-person training events and learning sessions.</p></div>{canManage&&<button onClick={()=>{setSelected(null);setShowForm(true)}}>+ Training Event</button>}</header>
    {error&&<div className="schedule-error">{error}<button onClick={()=>setError("")}>×</button></div>}
    <section className="schedule-calendar"><header><button onClick={()=>setCursor(new Date())}>Today</button><button aria-label="Previous month" onClick={()=>shift(-1)}>‹</button><button aria-label="Next month" onClick={()=>shift(1)}>›</button><h2>{monthTitle(cursor)}</h2><span>Month</span></header><div className="schedule-weekdays">{["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"].map(day=><b key={day}>{day}</b>)}</div><div className="schedule-grid">{days.map(day=><article className={`${day.getMonth()===cursor.getMonth()?"":"outside"} ${day.toDateString()===new Date().toDateString()?"today":""}`} key={day.toISOString()}><time>{day.getDate()}</time><div>{eventsFor(day).map(item=><button key={item.id} className={item.status} onClick={()=>{setSelected(item);setShowForm(canManage)}}><b>{new Date(item.starts_at).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}</b> {item.title}</button>)}</div></article>)}</div></section>
    {showForm&&canManage&&<div className="schedule-backdrop" onMouseDown={()=>setShowForm(false)}><form className="schedule-modal" onSubmit={submit} onMouseDown={event=>event.stopPropagation()}><header><div><small>LEARNING &amp; DEVELOPMENT</small><h2>{selected?"Edit Training Event":"Create Training Event"}</h2></div><button type="button" onClick={()=>setShowForm(false)}>×</button></header><div><label className="full">Event Title<input name="title" required defaultValue={selected?.title}/></label><label>Start<input name="startsAt" type="datetime-local" required defaultValue={selected?localInput(selected.starts_at):""}/></label><label>End<input name="endsAt" type="datetime-local" required defaultValue={selected?localInput(selected.ends_at):""}/></label><label>Venue<input name="venue" defaultValue={selected?.venue}/></label><label>Trainer<input name="trainer" defaultValue={selected?.trainer}/></label><label>Capacity<input name="capacity" type="number" min="1" defaultValue={selected?.capacity}/></label><label>Status<select name="status" defaultValue={selected?.status??"scheduled"}><option value="draft">Draft</option><option value="scheduled">Scheduled</option><option value="cancelled">Cancelled</option></select></label><label className="full">Description<textarea name="description" rows={4} defaultValue={selected?.description}/></label></div><footer>{selected&&<button type="button" className="danger" onClick={()=>void remove()}>Remove</button>}<button type="button" onClick={()=>setShowForm(false)}>Cancel</button><button>Save Event</button></footer></form></div>}
  </div>
}
