ALTER TABLE employees ADD COLUMN IF NOT EXISTS name_mm varchar(180);
ALTER TABLE employees ADD COLUMN IF NOT EXISTS organization varchar(180);
ALTER TABLE employees ADD COLUMN IF NOT EXISTS project_location varchar(180);
ALTER TABLE employees ADD COLUMN IF NOT EXISTS nrc_no_mm varchar(100);
ALTER TABLE employees ADD COLUMN IF NOT EXISTS nrc_no_eng varchar(100);
ALTER TABLE employees ADD COLUMN IF NOT EXISTS date_of_birth date;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS age integer CHECK(age IS NULL OR age BETWEEN 14 AND 100);
ALTER TABLE employees ADD COLUMN IF NOT EXISTS permanent_date date;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS service_year numeric(6,2);
ALTER TABLE employees ADD COLUMN IF NOT EXISTS gender varchar(30);
ALTER TABLE employees ADD COLUMN IF NOT EXISTS blood_type varchar(10);
ALTER TABLE employees ADD COLUMN IF NOT EXISTS father_name varchar(180);
ALTER TABLE employees ADD COLUMN IF NOT EXISTS marital_status varchar(30);
ALTER TABLE employees ADD COLUMN IF NOT EXISTS has_children boolean;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS number_of_children integer CHECK(number_of_children IS NULL OR number_of_children >= 0);
ALTER TABLE employees ADD COLUMN IF NOT EXISTS nationality varchar(80);
ALTER TABLE employees ADD COLUMN IF NOT EXISTS education text;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS other_qualification text;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS business_phone_no varchar(50);
ALTER TABLE employees ADD COLUMN IF NOT EXISTS business_email varchar(180);
ALTER TABLE employees ADD COLUMN IF NOT EXISTS current_address text;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS employment_type varchar(40);
ALTER TABLE employees ADD COLUMN IF NOT EXISTS branch varchar(120);
ALTER TABLE employees ADD COLUMN IF NOT EXISTS separation_date date;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS shift_required boolean;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS bank_account_pay_number varchar(120);
