from pathlib import Path
from reportlab.lib.colors import HexColor, white
from reportlab.lib.pagesizes import A4, landscape
from reportlab.pdfgen import canvas

output = Path(__file__).resolve().parents[1] / "output" / "pdf" / "Learning_Certificate_Design.pdf"
output.parent.mkdir(parents=True, exist_ok=True)
width, height = landscape(A4)
navy = HexColor("#071B4F")
gold = HexColor("#FFCC00")
muted = HexColor("#657381")

c = canvas.Canvas(str(output), pagesize=(width, height))
c.setFillColor(white)
c.rect(0, 0, width, height, fill=1, stroke=0)
c.setStrokeColor(navy)
c.setLineWidth(3)
c.rect(18, 18, width - 36, height - 36, fill=0, stroke=1)
c.setStrokeColor(gold)
c.setLineWidth(1.5)
c.rect(26, 26, width - 52, height - 52, fill=0, stroke=1)
c.setFillColor(navy)
c.rect(30, height - 95, width - 60, 55, fill=1, stroke=0)
c.setFillColor(gold)
c.rect(30, height - 102, width - 60, 7, fill=1, stroke=0)
c.setFillColor(white)
c.setFont("Helvetica-Bold", 13)
c.drawString(58, height - 72, "ATOZ GROUP")
c.setFont("Helvetica", 9)
c.drawRightString(width - 58, height - 72, "LEARNING & DEVELOPMENT")
c.setFillColor(navy)
c.setFont("Helvetica-Bold", 30)
c.drawCentredString(width / 2, height - 160, "CERTIFICATE OF COMPLETION")
c.setFillColor(muted)
c.setFont("Helvetica", 12)
c.drawCentredString(width / 2, height - 205, "This certificate is proudly presented to")
c.setFillColor(navy)
c.setFont("Helvetica-Bold", 27)
c.drawCentredString(width / 2, height - 253, "EMPLOYEE NAME")
c.setStrokeColor(gold)
c.setLineWidth(2)
c.line(235, height - 269, width - 235, height - 269)
c.setFillColor(muted)
c.setFont("Helvetica", 12)
c.drawCentredString(width / 2, height - 303, "for successfully completing the course")
c.setFillColor(navy)
c.setFont("Helvetica-Bold", 20)
c.drawCentredString(width / 2, height - 345, "COURSE TITLE")
items = [(130, "COMPLETION DATE", "19 August 2026"), (350, "CERTIFICATE ID", "LMS-2026-A1B2C3D4"), (650, "FINAL SCORE", "85%")]
for x, label, value in items:
    c.setFillColor(muted)
    c.setFont("Helvetica", 10)
    c.drawString(x, 174, label)
    c.setFillColor(navy)
    c.setFont("Helvetica-Bold", 13)
    c.drawString(x, 151, value)
c.setStrokeColor(HexColor("#A6B1BD"))
c.setLineWidth(1)
c.line(width - 257, 92, width - 82, 92)
c.setFillColor(muted)
c.setFont("Helvetica", 9)
c.drawCentredString(width - 169, 76, "AUTHORIZED SIGNATURE")
c.setFont("Helvetica", 8)
c.drawString(52, 48, "Verified digital certificate - Company Portal Learning Management")
c.showPage()
c.save()
print(output)
